language: android
before_install:
  - chmod +x gradlew
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - android-26
    - build-tools-26.0.1
    - extra-android-m2repository
    - extra-google-google_play_services
    - sys-img-armeabi-v7a-android-16

script:
   - ./gradlew build connectedCheck