language: android
before_install:
  - chmod +x gradlew
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-25.0.3
    - android-25
    - extra-android-m2repository

script:
   - ./gradlew build connectedCheck