package com.taskdesignsinc.android.myanimeviewer.model;

import java.util.Comparator;
import java.util.Date;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Keep;
import io.objectbox.annotation.Relation;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.Uid;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.BoxStore;
import io.objectbox.relation.ToOne;

@Entity
public class Episode {

    @Id
    long id;
    @Relation
    Anime anime;
    int index;
    String title;
    String url;
    Date date;
    String videoUrl;
    boolean isViewed = false;
    String localPath;
    long playPosition = 0;
    String animeUrl;

    @Override
    public String toString() {
        return "Episode [name=" + title + ", "
                + "url=" + url + ", "
                + "animeUrl=" + animeUrl + ", "
                + "index=" + index + ", "
                + "videoUrl=" + videoUrl + ", "
                + "isViewed=" + isViewed + ", "
                + "date=" + date + ", "
                + "localPath=" + localPath + " "
                + "playPosition=" + localPath + " "
                + "]";
    }

    /** To-one relationship, resolved on first access. */
    @Generated(697412469)
    public Anime getAnime() {
        anime = animeToOne.getTarget();
        return anime;
    }

    /** Set the to-one relation including its ID property. */
    @Keep
    public void setAnime(Anime anime) {
        animeToOne.setTarget(anime);
        this.anime = anime;
        this.animeUrl = anime.getUrl();
    }

    public static Comparator<Episode> SortByPosition = new Comparator<Episode>() {

        public int compare(Episode pEpisode1, Episode pEpisode2) {

            int diff = pEpisode1.index - pEpisode2.index;

            // ascending order
            return diff;
        }
    };
    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;

    @Generated(122010498)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public Episode(long id, int index, String title, String url, Date date,
            String videoUrl, boolean isViewed, String localPath, long playPosition,
            String animeUrl, long animeId) {
        this.id = id;
        this.index = index;
        this.title = title;
        this.url = url;
        this.date = date;
        this.videoUrl = videoUrl;
        this.isViewed = isViewed;
        this.localPath = localPath;
        this.playPosition = playPosition;
        this.animeUrl = animeUrl;
        this.animeToOne.setTargetId(animeId);
    }

    @Generated(1336866052)
    public Episode() {
    }

    @Internal
    @Generated(1721299457)
    transient ToOne<Anime> animeToOne = new ToOne<>(this, Episode_.anime);

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public int getIndex() {
        return index;
    }

    public void setIndex(int index) {
        this.index = index;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public String getVideoUrl() {
        return videoUrl;
    }

    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }

    public boolean isViewed() {
        return isViewed;
    }

    public void setViewed(boolean viewed) {
        isViewed = viewed;
    }

    public String getLocalPath() {
        return localPath;
    }

    public void setLocalPath(String localPath) {
        this.localPath = localPath;
    }

    public long getPlayPosition() {
        return playPosition;
    }

    public void setPlayPosition(long playPosition) {
        this.playPosition = playPosition;
    }

    public String getAnimeUrl() {
        return animeUrl;
    }

    public void setAnimeUrl(String animeUrl) {
        this.animeUrl = animeUrl;
    }
}
