package com.taskdesignsinc.android.myanimeviewer.model;

import io.objectbox.BoxStore;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Relation;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.relation.ToOne;

@Entity
public class FavoriteRecord {
    @Id
    private long id = 0;
    private String animeUrl = "";
    private int tagId = -1;

    @Relation
    private Anime anime;
    /**
     * Used to resolve relations
     */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;

    @Generated(1556071527)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public FavoriteRecord(long id, String animeUrl, int tagId, long animeId) {
        this.id = id;
        this.animeUrl = animeUrl;
        this.tagId = tagId;
        this.animeToOne.setTargetId(animeId);
    }

    @Generated(1447135516)
    public FavoriteRecord() {
    }

    @Internal
    @Generated(1223043601)
    transient ToOne<Anime> animeToOne = new ToOne<>(this, FavoriteRecord_.anime);

    @Override
    public String toString() {
        return "FavoriteObject [animeUrl=" + animeUrl + ", tagId=" + tagId + "]";
    }

    /**
     * @return the ID
     */
    public long getId() {
        return id;
    }

    /**
     * @param id the ID to set
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * @return the mAnimeUrl
     */
    public String getAnimeUrl() {
        return animeUrl;
    }

    /**
     * @param animeUrl the AnimeURL to set
     */
    public void setAnimeUrl(String animeUrl) {
        this.animeUrl = animeUrl;
    }

    public int getTagId() {
        return tagId;
    }

    public void setTagId(int tagId) {
        this.tagId = tagId;
    }

    /**
     * To-one relationship, resolved on first access.
     */
    @Generated(697412469)
    public Anime getAnime() {
        anime = animeToOne.getTarget();
        return anime;
    }

    /**
     * Set the to-one relation including its ID property.
     */
    @Generated(319411835)
    public void setAnime(Anime anime) {
        animeToOne.setTarget(anime);
        this.anime = anime;
    }
}
