package com.taskdesignsinc.android.myanimeviewer.model;

import com.taskdesignsinc.android.myanimeviewer.MAVApplication;

import java.util.Comparator;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Transient;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;

@Entity
public class HistoryRecord {

    @Id
    private long id = 0;
    private String animeUrl = "";
    private String episodeUrl = "";
    private String videoUrl = "";
    private long playPosition = 0;
    private long timeStamp = -1;
    private boolean isViewed = false;

    @Transient
    private Anime mAnime = null;
    @Transient
    private Episode mEpisode = null;

    public HistoryRecord() {
    }

    @Generated(1745666619)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public HistoryRecord(long id, String animeUrl, String episodeUrl, String videoUrl,
            long playPosition, long timeStamp, boolean isViewed) {
        this.id = id;
        this.animeUrl = animeUrl;
        this.episodeUrl = episodeUrl;
        this.videoUrl = videoUrl;
        this.playPosition = playPosition;
        this.timeStamp = timeStamp;
        this.isViewed = isViewed;
    }

    /**
     * @return the animeUrl
     */
    public String getAnimeUrl() {
        return animeUrl;
    }

    /**
     * @param pAnimeURL the AnimeURL to set
     */
    public void setAnimeUrl(String pAnimeURL) {
        this.animeUrl = pAnimeURL;
    }

    /**
     * @return the episodeUrl
     */
    public String getEpisodeUrl() {
        return episodeUrl;
    }

    /**
     * @param episodeUrl the EpisodeURL to set
     */
    public void setEpisodeUrl(String episodeUrl) {
        this.episodeUrl = episodeUrl;
    }

    /**
     * @return the timeStamp
     */
    public long getTimeStamp() {
        return timeStamp;
    }

    /**
     * @param timeStamp the TimeStamp to set
     */
    public void setTimeStamp(long timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * @return the manga
     */
    public Anime getAnime() {
        if (mAnime == null)
            mAnime = MAVApplication.getInstance().getRepository().getAnimeByUrl(animeUrl);
        return mAnime;
    }

    /**
     * @return the chapter
     */
    public Episode getEpisode() {
        if (mEpisode == null)
            mEpisode = MAVApplication.getInstance().getRepository().getEpisodeByUrl(episodeUrl);
        return mEpisode;
    }

    /**
     * @return the isViewed
     */
    public boolean isViewed() {
        return isViewed;
    }

    /**
     * @param isViewed the isViewed to set
     */
    public void setIsViewed(boolean isViewed) {
        this.isViewed = isViewed;
    }

    public long getPlayPosition() {
        return playPosition;
    }

    public void setPlayPosition(long pPlayPosition) {
        playPosition = pPlayPosition;
    }

    /**
     * @return the videoURL
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * @param videoUrl the videoURL to set
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public boolean getIsViewed() {
        return isViewed;
    }

    public static Comparator<HistoryRecord> SortByTimeStampASC = new Comparator<HistoryRecord>() {

        @Override
        public int compare(HistoryRecord pRecord1, HistoryRecord pRecord2) {

            int diff = (int) (pRecord1.getTimeStamp() - pRecord2.getTimeStamp());

            // ascending order
            return diff;
        }
    };

    public static Comparator<HistoryRecord> SortByTimeStampDESC = new Comparator<HistoryRecord>() {

        @Override
        public int compare(HistoryRecord pRecord1, HistoryRecord pRecord2) {

            int diff = (int) (pRecord2.getTimeStamp() - pRecord1.getTimeStamp());

            // ascending order
            return diff;
        }
    };
}
